package tank.mods.microworld.mobs.multicellular;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class WormAnimations {

public static final AnimationDefinition WORM_IDLE = AnimationDefinition.Builder.withLength(2.5416765f).looping()
	.addAnimation("bone1",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 1f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 2f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone2",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 1f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 1f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone3",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, -1f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone5",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 2f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, -0.17f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, 0.39f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone6",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 1f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone8",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, -1f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone9",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, -1f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition WORM_ATTACK = AnimationDefinition.Builder.withLength(1.9583433f)
	.addAnimation("bone1",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, -5f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.9583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone2",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, -4f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.9583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone3",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, -3f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.9583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone4",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, -2f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.9583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone5",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.125f, KeyframeAnimations.posVec(1f, -1f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.9583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone5",
		new AnimationChannel(AnimationChannel.Targets.SCALE,
			new Keyframe(1.125f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone6",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, 2f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.9583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone7",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, 3f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.9583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone8",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, 4f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.9583433f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition WORM_SWEEM = AnimationDefinition.Builder.withLength(3.5416765f)
	.addAnimation("bone1",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(-1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5834335f, KeyframeAnimations.posVec(1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(3.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone3",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5834335f, KeyframeAnimations.posVec(-1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(3.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone5",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(-1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5834335f, KeyframeAnimations.posVec(1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(3.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone7",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5834335f, KeyframeAnimations.posVec(-1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(3.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone8",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5834335f, KeyframeAnimations.posVec(1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(3.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone9",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(2f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(2.5834335f, KeyframeAnimations.posVec(-1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(3.5416765f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	
	public static final AnimationDefinition WORM_DAMAGED = AnimationDefinition.Builder.withLength(1.375f)
	.addAnimation("bone1",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 3f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone2",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 3f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone3",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 1f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone4",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(1f, -2f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone4",
		new AnimationChannel(AnimationChannel.Targets.SCALE,
			new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1f, KeyframeAnimations.scaleVec(1.7f, 1.7f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone5",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone6",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -3f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone7",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -5f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone7",
		new AnimationChannel(AnimationChannel.Targets.SCALE,
			new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1f, KeyframeAnimations.scaleVec(0.7f, 0.7f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(1.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone8",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -7f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("bone9",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -7f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
}
