package tank.mods.microworld.items;

import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import tank.mods.microworld.MicroworldMod;
import tank.mods.microworld.items.custom.DarkCoreItem;
import tank.mods.microworld.items.custom.FlagellarMotorItem;
import tank.mods.microworld.items.custom.FoodPouchItem;
import tank.mods.microworld.items.custom.MagnifierItem;
import tank.mods.microworld.items.custom.MicroportalItem;
import tank.mods.microworld.items.custom.Organ_xItem;
import tank.mods.microworld.items.custom.SpiritBubbleItem;
import tank.mods.microworld.items.custom.VacuoleItem;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;

/**
 * All the items of mod. Code is particularly generated by excel formulas, it's very same type
 * 
 */
public class ModItems {

	public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, MicroworldMod.MODID);
	
	
	// From "temnarik" mod, just for fun :)
	public static final RegistryObject<Item> DARK_CORE = ITEMS.register("dark_core",
	        () -> new DarkCoreItem(new Item.Properties().stacksTo(1).durability(10)));
	public static final RegistryObject<Item> RAW_DARK_CORE = ITEMS.register("raw_dark_core", 
			() -> new Item(new Item.Properties()));
	
	/*
	 * Код сгенерировал при помощи формулы в табличках. Да здравствует мощь экселя, ой, гугл доков!
	 * */
	public static final RegistryObject<Item> microportal = ITEMS.register("microportal", () -> new MicroportalItem(new Item.Properties()));
	public static final RegistryObject<Item> magnifier = ITEMS.register("magnifier", () -> new MagnifierItem(new Item.Properties()));

	public static final RegistryObject<Item> endoplasm = ITEMS.register("endoplasm", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> lysosome = ITEMS.register("lysosome", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> nucleus = ITEMS.register("nucleus", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> chitin = ITEMS.register("chitin", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> sticky_stuff = ITEMS.register("sticky_stuff", () -> new ModItemBase(new Item.Properties()));
	
	public static final RegistryObject<Item> ribosome = ITEMS.register("ribosome", () -> new ModItemBase(new Item.Properties().food(new FoodProperties.Builder().nutrition(4).saturationMod(0.3f).build())));
	public static final RegistryObject<Item> organ_x = ITEMS.register("organ_x", () -> new Organ_xItem(new Item.Properties()));
	public static final RegistryObject<Item> vacuole = ITEMS.register("vacuole", () -> new VacuoleItem(new Item.Properties()));

	public static final RegistryObject<Item> membrane_piece = ITEMS.register("membrane_piece", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> strange_cell = ITEMS.register("strange_cell", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> chlorophyll = ITEMS.register("chlorophyll", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> flagellum = ITEMS.register("flagellum", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> funiculus = ITEMS.register("funiculus", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> spirit_bubble = ITEMS.register("spirit_bubble", () -> new SpiritBubbleItem(new Item.Properties()));
	public static final RegistryObject<Item> germ = ITEMS.register("germ", () -> new ModItemBase(new Item.Properties()));

	public static final RegistryObject<Item> amoebic_slurry = ITEMS.register("amoebic_slurry", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> rotifier_fan = ITEMS.register("rotifier_fan", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> microdudka = ITEMS.register("microdudka", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> stinging_cell = ITEMS.register("stinging_cell", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> worm_fragment = ITEMS.register("worm_fragment", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> bedroсk_piece = ITEMS.register("bedrock_piece", () -> new ModItemBase(new Item.Properties()));


	public static final RegistryObject<Item> flagellar_motor = ITEMS.register("flagellar_motor", () -> new FlagellarMotorItem(new Item.Properties()));
	public static final RegistryObject<Item> food_pouch = ITEMS.register("food_pouch", () -> new FoodPouchItem(new Item.Properties()));
	public static final RegistryObject<Item> germ_boots = ITEMS.register("germ_boots", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> poison_bomb = ITEMS.register("poison_bomb", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> sanitizer = ITEMS.register("sanitizer", () -> new ModItemBase(new Item.Properties()));

	public static final RegistryObject<Item> stinging_sword = ITEMS.register("stinging_sword", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> cell_shuriken = ITEMS.register("cell_shuriken", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> superpipe = ITEMS.register("superpipe", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> anti_infusor_spike = ITEMS.register("anti_infusor_spike", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> microbial_builder = ITEMS.register("microbial_builder", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> sticky_shield = ITEMS.register("sticky_shield", () -> new ModItemBase(new Item.Properties()));
	public static final RegistryObject<Item> nematode_pick = ITEMS.register("nematode_pick", () -> new ModItemBase(new Item.Properties()));

	public static final RegistryObject<Item> ayubov_submarine = ITEMS.register("ayubov_submarine", () -> new ModItemBase(new Item.Properties()));

    public static final RegistryObject<Item> BEDROCK_HELMET = ITEMS.register("bedrock_helmet",
            () -> new ModArmorItem(ModArmorMaterials.BEDROCK, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> BEDROCK_CHESTPLATE = ITEMS.register("bedrock_chestplate",
            () -> new ModArmorItem(ModArmorMaterials.BEDROCK, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> BEDROCK_LEGGINGS = ITEMS.register("bedrock_leggings",
            () -> new ModArmorItem(ModArmorMaterials.BEDROCK, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> BEDROCK_BOOTS = ITEMS.register("bedrock_boots",
            () -> new ModArmorItem(ModArmorMaterials.BEDROCK, ArmorItem.Type.BOOTS, new Item.Properties()));
	
	public static final RegistryObject<Item> CHITIN_HELMET = ITEMS.register("chitin_helmet",
            () -> new ModArmorItem(ModArmorMaterials.CHITIN, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> CHITIN_CHESTPLATE = ITEMS.register("chitin_chestplate",
            () -> new ModArmorItem(ModArmorMaterials.CHITIN, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> CHITIN_LEGGINGS = ITEMS.register("chitin_leggings",
            () -> new ModArmorItem(ModArmorMaterials.CHITIN, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> CHITIN_BOOTS = ITEMS.register("chitin_boots",
            () -> new ModArmorItem(ModArmorMaterials.CHITIN, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> CILLIARY_HELMET = ITEMS.register("cilliary_helmet",
            () -> new ModArmorItem(ModArmorMaterials.CILLIARY, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> CILLIARY_CHESTPLATE = ITEMS.register("cilliary_chestplate",
            () -> new ModArmorItem(ModArmorMaterials.CILLIARY, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> CILLIARY_LEGGINGS = ITEMS.register("cilliary_leggings",
            () -> new ModArmorItem(ModArmorMaterials.CILLIARY, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> CILLIARY_BOOTS = ITEMS.register("cilliary_boots",
            () -> new ModArmorItem(ModArmorMaterials.CILLIARY, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> FLEX_HELMET = ITEMS.register("flex_helmet",
            () -> new ModArmorItem(ModArmorMaterials.FLEX, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> FLEX_CHESTPLATE = ITEMS.register("flex_chestplate",
            () -> new ModArmorItem(ModArmorMaterials.FLEX, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> FLEX_LEGGINGS = ITEMS.register("flex_leggings",
            () -> new ModArmorItem(ModArmorMaterials.FLEX, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> FLEX_BOOTS = ITEMS.register("flex_boots",
            () -> new ModArmorItem(ModArmorMaterials.FLEX, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> STICKY_HELMET = ITEMS.register("sticky_helmet",
            () -> new ModArmorItem(ModArmorMaterials.STICKY, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> STICKY_CHESTPLATE = ITEMS.register("sticky_chestplate",
            () -> new ModArmorItem(ModArmorMaterials.STICKY, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> STICKY_LEGGINGS = ITEMS.register("sticky_leggings",
            () -> new ModArmorItem(ModArmorMaterials.STICKY, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> STICKY_BOOTS = ITEMS.register("sticky_boots",
            () -> new ModArmorItem(ModArmorMaterials.STICKY, ArmorItem.Type.BOOTS, new Item.Properties()));


	public static void register(IEventBus eventBus) {
		ITEMS.register(eventBus);
	}
}
